-- MySQL Script generated by MySQL Workbench
-- Tue Feb 10 11:03:57 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Carteira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carteira` (
  `id_carteira` INT NOT NULL AUTO_INCREMENT,
  `Moeda` VARCHAR(16) NOT NULL,
  `saldo_atual` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_carteira`));


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Nome_Completo` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `nivel` INT NOT NULL,
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `Carteira_id_carteira` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_Usuario_Carteira_idx` (`Carteira_id_carteira` ASC) VISIBLE,
  UNIQUE INDEX `uq_Usuario_Carteira` (`Carteira_id_carteira` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Carteira`
    FOREIGN KEY (`Carteira_id_carteira`)
    REFERENCES `mydb`.`Carteira` (`id_carteira`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genero` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_genero`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `Titulo` VARCHAR(100) NOT NULL,
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `preço` DECIMAL(10,2) NOT NULL,
  `Descricao` VARCHAR(255) NOT NULL,
  `Data_lancamento` DATE NOT NULL,
  `Publicadora_Nome_Publicadora` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_produto`));


-- -----------------------------------------------------
-- Table `mydb`.`Jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jogos` (
  `Suporte_Controle` TINYINT NOT NULL,
  `Faixa_etaria` VARCHAR(45) NOT NULL,
  `Produto_id_produto` INT NOT NULL,
  `idiomas` VARCHAR(45) NOT NULL,
  `Nome_empresa` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Produto_id_produto`),
  INDEX `fk_Jogos_Desenvolvedora_idx` (`Nome_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_Jogos_Produto1`
    FOREIGN KEY (`Produto_id_produto`)
    REFERENCES `mydb`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogos_Desenvolvedora1`
    FOREIGN KEY (`Nome_empresa`)
    REFERENCES `mydb`.`Desenvolvedora` (`Nome_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Desenvolvedora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Desenvolvedora` (
  `Nome_empresa` VARCHAR(255) NOT NULL,
  `pais_sede` VARCHAR(45) NOT NULL,
  `website` VARCHAR(100) NULL,
  PRIMARY KEY (`Nome_empresa`));


-- -----------------------------------------------------
-- Table `mydb`.`Publicadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publicadora` (
  `Nome_Publicadora` VARCHAR(255) NOT NULL,
  `contato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nome_Publicadora`));

ALTER TABLE `mydb`.`Produto`
  ADD INDEX `fk_Produto_Publicadora_idx` (`Publicadora_Nome_Publicadora` ASC) VISIBLE,
  ADD CONSTRAINT `fk_Produto_Publicadora`
    FOREIGN KEY (`Publicadora_Nome_Publicadora`)
    REFERENCES `mydb`.`Publicadora` (`Nome_Publicadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;


-- -----------------------------------------------------
-- Table `mydb`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avaliacao` (
  `voto` TINYINT NULL,
  `Texto_analise` VARCHAR(255) NULL,
  `data_postagem` DATETIME NULL,
  `Usuario_id_usuario` INT NOT NULL,
  `Jogos_Produto_id_produto` INT NOT NULL,
  INDEX `fk_Avaliação_Usuario1_idx` (`Usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_Avaliação_Jogos1_idx` (`Jogos_Produto_id_produto` ASC) VISIBLE,
  PRIMARY KEY (`Jogos_Produto_id_produto`, `Usuario_id_usuario`),
  CONSTRAINT `fk_Avaliação_Usuario1`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliação_Jogos1`
    FOREIGN KEY (`Jogos_Produto_id_produto`)
    REFERENCES `mydb`.`Jogos` (`Produto_id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Biblioteca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Biblioteca` (
  `tempo_jogado` INT NULL,
  `status_instalacao` TINYINT NOT NULL,
  `Usuario_id_usuario1` INT NOT NULL,
  PRIMARY KEY (`Usuario_id_usuario1`),
  INDEX `fk_Biblioteca_Usuario1_idx` (`Usuario_id_usuario1` ASC) VISIBLE,
  CONSTRAINT `fk_Biblioteca_Usuario1`
    FOREIGN KEY (`Usuario_id_usuario1`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `status` TINYINT NOT NULL,
  `metodo_pagamento` VARCHAR(32) NOT NULL,
  `valor_pago` DECIMAL(10,2) NOT NULL,
  `data_compra` DATETIME NOT NULL,
  `Produto_id_produto` INT NOT NULL,
  `Usuario_id_usuario` INT NOT NULL,
  INDEX `fk_Compra_Produto1_idx` (`Produto_id_produto` ASC) INVISIBLE,
  INDEX `fk_Compra_Usuario1_idx` (`Usuario_id_usuario` ASC) INVISIBLE,
  PRIMARY KEY (`id_compra`),
  CONSTRAINT `fk_Compra_Produto1`
    FOREIGN KEY (`Produto_id_produto`)
    REFERENCES `mydb`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Usuario1`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Nota_Fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nota_Fiscal` (
  `id_nota` INT NOT NULL AUTO_INCREMENT,
  `numero_serie` INT NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `data_emissao` DATETIME NOT NULL,
  `Compra_id_compra` INT NOT NULL,
  PRIMARY KEY (`id_nota`),
  INDEX `fk_Nota Fiscal_Compra1_idx` (`Compra_id_compra` ASC) VISIBLE,
  CONSTRAINT `fk_Nota Fiscal_Compra1`
    FOREIGN KEY (`Compra_id_compra`)
    REFERENCES `mydb`.`Compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Conquista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conquista` (
  `Titulo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `imagem_icone` BLOB NOT NULL,
  `id_conquista` INT NOT NULL,
  `Jogos_Produto_id_produto` INT NOT NULL,
  PRIMARY KEY (`id_conquista`, `Jogos_Produto_id_produto`),
  INDEX `fk_Conquista_Jogos1_idx` (`Jogos_Produto_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_Conquista_Jogos1`
    FOREIGN KEY (`Jogos_Produto_id_produto`)
    REFERENCES `mydb`.`Jogos` (`Produto_id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RequisitoSistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RequisitoSistema` (
  `CPU` VARCHAR(46) NULL,
  `sistema_operacional` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `Jogos_Produto_id_produto` INT NOT NULL,
  `GPU` VARCHAR(45) NULL,
  `Memoria_ram` VARCHAR(45) NULL,
  `armazenamento_disco` VARCHAR(45) NULL,
  INDEX `fk_RequisitoSistema_Jogos1_idx` (`Jogos_Produto_id_produto` ASC) VISIBLE,
  PRIMARY KEY (`Jogos_Produto_id_produto`, `tipo`),
  CONSTRAINT `fk_RequisitoSistema_Jogos1`
    FOREIGN KEY (`Jogos_Produto_id_produto`)
    REFERENCES `mydb`.`Jogos` (`Produto_id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Software`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Software` (
  `versao_software` VARCHAR(32) NOT NULL,
  `tipo_licenca` VARCHAR(45) NOT NULL,
  `Produto_id_produto` INT NOT NULL,
  PRIMARY KEY (`Produto_id_produto`),
  INDEX `fk_Software_Produto1_idx` (`Produto_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_Software_Produto1`
    FOREIGN KEY (`Produto_id_produto`)
    REFERENCES `mydb`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DLC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DLC` (
  `requer_jogo_base` TINYINT NOT NULL,
  `tamanho_download` INT NOT NULL,
  `Produto_id_produto` INT NOT NULL,
  PRIMARY KEY (`Produto_id_produto`),
  CONSTRAINT `fk_DLC_Produto1`
    FOREIGN KEY (`Produto_id_produto`)
    REFERENCES `mydb`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jogos_has_Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jogos_has_Genero` (
  `Jogos_Produto_id_produto` INT NOT NULL,
  `Genero_id_genero` INT NOT NULL,
  INDEX `fk_Jogos_has_Genero_Genero1_idx` (`Genero_id_genero` ASC) VISIBLE,
  INDEX `fk_Jogos_has_Genero_Jogos1_idx` (`Jogos_Produto_id_produto` ASC) VISIBLE,
  PRIMARY KEY (`Genero_id_genero`, `Jogos_Produto_id_produto`),
  CONSTRAINT `fk_Jogos_has_Genero_Jogos1`
    FOREIGN KEY (`Jogos_Produto_id_produto`)
    REFERENCES `mydb`.`Jogos` (`Produto_id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogos_has_Genero_Genero1`
    FOREIGN KEY (`Genero_id_genero`)
    REFERENCES `mydb`.`Genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Biblioteca_has_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Biblioteca_has_Produto` (
  `Biblioteca_Usuario_id_usuario1` INT NOT NULL,
  `Produto_id_produto` INT NOT NULL,
  INDEX `fk_Biblioteca_has_Produto_Produto1_idx` (`Produto_id_produto` ASC) VISIBLE,
  INDEX `fk_Biblioteca_has_Produto_Biblioteca1_idx` (`Biblioteca_Usuario_id_usuario1` ASC) VISIBLE,
  PRIMARY KEY (`Produto_id_produto`, `Biblioteca_Usuario_id_usuario1`),
  CONSTRAINT `fk_Biblioteca_has_Produto_Biblioteca1`
    FOREIGN KEY (`Biblioteca_Usuario_id_usuario1`)
    REFERENCES `mydb`.`Biblioteca` (`Usuario_id_usuario1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Biblioteca_has_Produto_Produto1`
    FOREIGN KEY (`Produto_id_produto`)
    REFERENCES `mydb`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

DELIMITER //

CREATE TRIGGER trg_usuario_biblioteca
AFTER INSERT ON Usuario
FOR EACH ROW
BEGIN
  INSERT INTO Biblioteca (Usuario_id_usuario1, status_instalacao)
  VALUES (NEW.id_usuario, 0);
END//

CREATE TRIGGER trg_compra_nota
AFTER INSERT ON Compra
FOR EACH ROW
BEGIN
  INSERT INTO Nota_Fiscal (numero_serie, valor_total, data_emissao, Compra_id_compra)
  VALUES (NEW.id_compra, NEW.valor_pago, NOW(), NEW.id_compra);
END//

DELIMITER ;
